- name: 'September AMT'
  meta: '25.10'
  url: 'https://tournaments.nullsignal.games/tournaments/4195'
- name: 'Norwich Pre-Worlds GNK'
  meta: '25.10'
  url: 'https://tournaments.nullsignal.games/tournaments/4198'
- name: 'Stirling CO'
  meta: '25.10'
  url: 'https://tournaments.nullsignal.games/tournaments/4197'
- name: 'NANPC Bay Area'
  meta: '25.10'
  url: 'https://tournaments.nullsignal.games/tournaments/4199'
- name: 'Rain City GNK'
  meta: '25.10'
  url: 'https://tournaments.nullsignal.games/tournaments/4200'
- name: 'Colorado Worlds Prep'
  meta: '25.10'
  url: 'https://tournaments.nullsignal.games/tournaments/4201'
- name: 'Helsinki CT'
  meta: '25.10'
  url: 'https://tournaments.nullsignal.games/tournaments/4203'
- name: 'Canberra Worlds warm up'
  meta: '25.10'
  url: 'https://tournaments.nullsignal.games/tournaments/4196'
- name: 'Worlds Showdown'
  meta: '25.10'
  url: 'https://tournaments.nullsignal.games/tournaments/4128'
  location: online
  abr_id: 4857
- name: '2025 World Championship'
  meta: '25.10'
  url: 'https://tournaments.nullsignal.games/tournaments/4255'
  abr_id: 5084
